create table if not exists sites (
  id text primary key,
  name text not null,
  url text not null unique,
  "group" text not null default 'custom',
  maintenance boolean not null default false
);

create table if not exists checks (
  id bigint generated by default as identity primary key,
  site_id text not null references sites(id) on delete cascade,
  checked_at timestamptz not null,
  status text not null check (status in ('online', 'offline')),
  response_time_ms integer
);

create index if not exists checks_site_time_idx on checks(site_id, checked_at desc);
insert into sites (id, name, url, "group") values
  ('strata-home', 'Strata Staff Global', 'https://stratastaffglobal.com/', 'core'),
  ('trackdev', 'TrackDev', 'https://dev.stratastaff.com/board', 'internal'),
  ('escalations', 'Escalations', 'https://escalations.stratastaffglobal.com/', 'internal'),
  ('newsletter', 'Newsletter Analytics', 'https://newsletter-analytics.stratastaff.com/', 'internal'),
  ('cng-tickets', 'CNG Tickets', 'https://cng-tickets.stratastaff.com/login.php', 'internal'),
  ('client-feedback', 'Client Feedback', 'https://clients-feedback.stratastaff.com/feedback.php', 'client'),
  ('scorecard', 'Strata Capacity Test', 'https://stratastaffglobal.com/scorecard/', 'internal'),
  ('icp-access', 'ICP Access', 'https://stratastaffglobal.com/icp/icp-login.php', 'internal'),
  ('srf-login', 'Staff Login (SRF)', 'https://stratastaff.com/srf/admin/login.php', 'internal'),
  ('signatures', 'Email Signature Generator', 'https://onboarding.stratastaffglobal.com/banner/stratastaff/', 'internal')
on conflict (id) do nothing;
