create table if not exists sites (
  id text primary key,
  name text not null,
  url text not null unique,
  "group" text not null default 'custom',
  maintenance boolean not null default false,
  sla_target numeric not null default 99
);

alter table sites add column if not exists sla_target numeric not null default 99;
update sites set "group" = 'Public Internal' where "group" = 'internal';
update sites set "group" = 'Private On-Premise' where "group" = 'private';

create table if not exists checks (
  id bigint generated by default as identity primary key,
  site_id text not null references sites(id) on delete cascade,
  checked_at timestamptz not null,
  status text not null check (status in ('online', 'offline')),
  response_time_ms integer
);

create index if not exists checks_site_time_idx on checks(site_id, checked_at desc);
create table if not exists monthly_summaries (
  site_id text not null references sites(id) on delete cascade,
  month date not null,
  uptime_percent numeric not null,
  incident_count integer not null,
  avg_response_time_ms integer,
  primary key (site_id, month)
);
create table if not exists report_status (
  id bigint generated by default as identity primary key,
  status text not null,
  sent_at timestamptz not null,
  reason text
);
insert into sites (id, name, url, "group") values
  ('strata-home', 'Strata Staff Global', 'https://stratastaffglobal.com/', 'Public'),
  ('trackdev', 'TrackDev', 'https://dev.stratastaff.com/board', 'internal'),
  ('escalations', 'Escalations', 'https://escalations.stratastaffglobal.com/', 'internal'),
  ('newsletter', 'Newsletter Analytics', 'https://newsletter-analytics.stratastaff.com/', 'internal'),
  ('cng-tickets', 'CNG Tickets', 'https://cng-tickets.stratastaff.com/login.php', 'internal'),
  ('client-feedback', 'Client Feedback', 'https://clients-feedback.stratastaff.com/feedback.php', 'Public Internal'),
  ('scorecard', 'Strata Capacity Test', 'https://stratastaffglobal.com/scorecard/', 'internal'),
  ('icp-access', 'ICP Access', 'https://stratastaffglobal.com/icp/icp-login.php', 'internal'),
  ('srf-login', 'Staff Login (SRF)', 'https://stratastaff.com/srf/admin/login.php', 'internal'),
  ('signatures', 'Email Signature Generator', 'https://onboarding.stratastaffglobal.com/banner/stratastaff/', 'internal'),
  ('strata-systems', 'Strata Systems Dashboard', 'https://strata-staff-systems.vercel.app/', 'Public'),
  ('grafana-private', 'GRAFANA Monitoring Servers', 'http://172.16.1.243:3000/', 'Private On-Premise'),
  ('support', 'Support', 'https://support.stratastaffglobal.com/', 'internal'),
  ('requisition', 'Requisition', 'https://requisition.stratastaffglobal.com/', 'internal'),
  ('afm', 'AFM', 'https://afm.stratastaffglobal.com/', 'internal'),
  ('analytics', 'Analytics', 'https://analytics.stratastaffglobal.com/', 'internal'),
  ('dashboard', 'Dashboard', 'https://dashboard.stratastaffglobal.com/', 'internal'),
  ('ca-hr-jobs', 'Canada HR Jobs', 'https://stratastaffglobal.com/ca/hr-jobs/', 'internal'),
  ('hr-jobs', 'HR Jobs', 'https://stratastaffglobal.com/hr-jobs/', 'internal'),
  ('academy', 'Academy', 'https://academy.stratastaffglobal.com/', 'internal'),
  ('crm', 'CRM', 'https://crm.stratastaffglobal.com/', 'internal'),
  ('learning', 'Learning Portal', 'https://learning.stratastaffglobal.com/public/', 'internal')
on conflict (id) do nothing;
