import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { jsPDF } from 'jspdf';
import { Activity, ArrowUpRight, Check, Clipboard, Moon, Plus, Search, Sun, Wrench, X } from 'lucide-react';
import { sites } from './sites';
import './styles.css';
import './modal.css';

const fallback = sites.map(site => ({ ...site, status: 'online', responseTime: null, httpStatus: null }));
const displayUrl = url => url.replace(/^https?:\/\//, '').replace(/\/$/, '');
const favicon = url => `https://www.google.com/s2/favicons?domain=${new URL(url).hostname}&sz=64`;
const directFavicon = url => `${new URL(url).origin}/favicon.ico`;

function App() {
  const [data, setData] = useState({ results: fallback, checkedAt: 0, maintenance: {} });
  const [query, setQuery] = useState('');
  const [dark, setDark] = useState(false);
  const [copied, setCopied] = useState(false);
  const [showAdd, setShowAdd] = useState(false);
  const [newSite, setNewSite] = useState({ name: '', url: '' });
  const [reportMonth, setReportMonth] = useState(new Date().toISOString().slice(0, 7));
  const [exporting, setExporting] = useState(false);

  const refresh = () => fetch('/api/check-status').then(r => r.json()).then(setData).catch(() => {});
  useEffect(() => { refresh(); const timer = setInterval(refresh, 120000); return () => clearInterval(timer); }, []);
  const filtered = useMemo(() => data.results.filter(site => site.name.toLowerCase().includes(query.toLowerCase())).sort((a, b) => (a.status === 'offline' ? -1 : 1) - (b.status === 'offline' ? -1 : 1)), [data.results, query]);
  const down = data.results.filter(site => site.status === 'offline' && !data.maintenance[site.id]).length;
  const checkedAgo = data.checkedAt ? Math.max(0, Math.round((Date.now() - data.checkedAt) / 1000)) : null;
  const toggleMaintenance = async site => { const maintenance = !data.maintenance[site.id]; const password = window.prompt(`Password to ${maintenance ? 'enable' : 'disable'} maintenance:`); if (password === null) return; const result = await fetch('/api/check-status', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: site.id, maintenance, password }) }); if (result.ok) setData({ ...data, maintenance: (await result.json()).maintenance }); else window.alert('Incorrect password.'); };
  const addSite = async event => { event.preventDefault(); const password = event.currentTarget.password.value; const result = await fetch('/api/check-status', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...newSite, action: 'add', password }) }); if (!result.ok) { const error = await result.json().catch(() => ({})); window.alert(error.error || 'Unable to add site.'); return; } setNewSite({ name: '', url: '' }); setShowAdd(false); refresh(); };
  const exportReport = async () => { setExporting(true); try { const from = `${reportMonth}-01T00:00:00.000Z`; const [year, month] = reportMonth.split('-').map(Number); const to = new Date(Date.UTC(year, month, 0, 23, 59, 59, 999)).toISOString(); const result = await fetch(`/api/report?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`); if (!result.ok) throw new Error('Report data unavailable.'); const report = await result.json(); const doc = new jsPDF({ unit: 'pt', format: 'a4' }); const left = 42; const pageWidth = doc.internal.pageSize.getWidth(); doc.setFillColor(248, 250, 249); doc.rect(0, 0, pageWidth, 92, 'F'); doc.setTextColor(20, 31, 29); doc.setFont('helvetica', 'bold'); doc.setFontSize(20); doc.text('STRATA SYSTEMS', left, 39); doc.setFont('courier', 'normal'); doc.setFontSize(9); doc.setTextColor(92, 108, 102); doc.text('MONTHLY AVAILABILITY REPORT', left, 59); doc.text(`${reportMonth}  /  generated ${new Date(report.generatedAt).toLocaleString()}`, left, 75); let y = 124; const cols = [left, 220, 325, 382, 450]; doc.setFillColor(31, 47, 43); doc.rect(left, y - 16, pageWidth - left * 2, 24, 'F'); doc.setTextColor(255, 255, 255); doc.setFont('courier', 'bold'); doc.setFontSize(8); ['SYSTEM / URL', 'UPTIME', 'INCIDENTS', 'AVG MS', 'STATUS'].forEach((label, index) => doc.text(label, cols[index], y)); y += 27; report.sites.forEach(site => { const checks = report.checks.filter(check => check.site_id === site.id || check.id === site.id); const incidents = checks.filter((check, index) => check.status === 'offline' && (index === 0 || checks[index - 1].status !== 'offline')).length; const uptime = checks.length ? `${((checks.filter(check => check.status === 'online').length / checks.length) * 100).toFixed(2)}%` : 'N/A'; const responseTimes = checks.map(check => check.response_time_ms ?? check.responseTime).filter(Number.isFinite); const average = responseTimes.length ? Math.round(responseTimes.reduce((sum, value) => sum + value, 0) / responseTimes.length) : 'N/A'; const current = data.results.find(item => item.id === site.id); if (y > 760) { doc.addPage(); y = 52; } doc.setFillColor(255, 255, 255); doc.setDrawColor(220, 227, 223); doc.line(left, y + 10, pageWidth - left, y + 10); doc.setTextColor(25, 39, 35); doc.setFont('helvetica', 'bold'); doc.setFontSize(9); doc.text(site.name.slice(0, 28), cols[0], y); doc.setFont('courier', 'normal'); doc.setFontSize(7); doc.setTextColor(104, 119, 112); doc.text(displayUrl(site.url).slice(0, 35), cols[0], y + 11); doc.setTextColor(34, 53, 47); doc.text(uptime, cols[1], y + 4); doc.text(String(incidents), cols[2], y + 4); doc.text(String(average), cols[3], y + 4); doc.text(current?.status === 'offline' ? 'OFFLINE' : site.maintenance ? 'MAINTENANCE' : 'ONLINE', cols[4], y + 4); y += 36; }); doc.save(`strata-systems-report-${reportMonth}.pdf`); } catch (error) { window.alert(error.message); } finally { setExporting(false); } };
  const share = () => { navigator.clipboard?.writeText(window.location.href); setCopied(true); setTimeout(() => setCopied(false), 1500); };

  return <div className={dark ? 'app dark' : 'app'}>
    <header className="topbar"><div className="brand"><span className="brand-mark"><Activity size={17}/></span><span>STRATA <b>SYSTEMS</b></span></div><div className="actions"><span className="env-label">PRODUCTION / LIVE</span><button className="add-site" onClick={() => setShowAdd(true)}><Plus size={14}/> Add site</button><button className="icon-btn" onClick={() => setDark(!dark)} aria-label="Toggle dark mode">{dark ? <Sun size={17}/> : <Moon size={17}/>}</button><button className="share" onClick={share}>{copied ? <Check size={14}/> : <Clipboard size={14}/>} {copied ? 'Copied' : 'Copy link'}</button></div></header>
    <main><section className="masthead"><div><p className="eyebrow">OPERATIONS / ENDPOINT MONITOR</p><h1>System status</h1><p className="subhead">Strata Staff Global infrastructure, checked continuously.</p></div><div className={`system-pill ${down ? 'danger' : 'healthy'}`}><span className="pulse"/><div><strong>{down ? `${down} system${down > 1 ? 's' : ''} down` : 'All systems operational'}</strong><small>{checkedAgo === null ? 'Checking now…' : `Last checked ${checkedAgo}s ago`}</small></div></div></section>
      <section className="toolbar"><label className="search"><Search size={16}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Filter endpoints…" aria-label="Search systems"/></label><div className="report-tools"><label className="month-picker">REPORT MONTH<input type="month" value={reportMonth} onChange={event => setReportMonth(event.target.value)}/></label><button className="export-report" onClick={exportReport} disabled={exporting}>{exporting ? 'Building…' : 'Export report'}</button><span className="count">{filtered.length} / {data.results.length} ENDPOINTS</span></div></section>
      <section className="status-table" aria-label="Monitored systems"><div className="table-head"><span>SYSTEM</span><span>STATUS</span><span>RESPONSE</span><span>LAST INCIDENT</span><span>ACTION</span></div>{filtered.map(site => { const maintenance = data.maintenance[site.id]; const status = maintenance ? 'maintenance' : site.status; return <article className={`status-row ${status}`} key={site.id}><a className="site-main" href={site.url} target="_blank" rel="noopener noreferrer"><span className="site-heading"><img src={favicon(site.url)} onError={event => { event.currentTarget.onerror = null; event.currentTarget.src = directFavicon(site.url); }} alt=""/><span><strong>{site.name}</strong><em>{displayUrl(site.url)}</em></span><ArrowUpRight className="external" size={16}/></span></a><span className={`status ${status}`}><i/>{status}</span><strong className="response-value">{site.responseTime ? `${site.responseTime} ms` : '—'}</strong><span className="incident">{site.lastIncident ? new Date(site.lastIncident).toLocaleString() : 'None recorded'}</span><button className={`maintenance ${maintenance ? 'active' : ''}`} onClick={() => toggleMaintenance(site)}><Wrench size={13}/>{maintenance ? 'Maintenance' : 'Set maintenance'}</button></article> })}</section>
    </main><footer><span><span className="footer-dot"/> Monitoring {data.results.length} endpoints</span><span>Auto-refreshes every 2 minutes</span></footer>
    {showAdd && <div className="modal-backdrop" role="presentation" onMouseDown={event => event.target === event.currentTarget && setShowAdd(false)}><form className="modal" onSubmit={addSite}><div className="modal-head"><div><p className="eyebrow">ENDPOINT REGISTRY</p><h2>Add monitored site</h2></div><button type="button" className="icon-btn" onClick={() => setShowAdd(false)} aria-label="Close"><X size={16}/></button></div><label>Site name<input required value={newSite.name} onChange={event => setNewSite({ ...newSite, name: event.target.value })} placeholder="e.g. Client Portal"/></label><label>URL<input required type="url" value={newSite.url} onChange={event => setNewSite({ ...newSite, url: event.target.value })} placeholder="https://example.com"/></label><label>Update password<input required name="password" type="password" inputMode="numeric" autoComplete="off" placeholder="123456"/></label><p className="modal-note">New sites are checked on the next status refresh.</p><button className="modal-submit" type="submit">Add site</button></form></div>}
  </div>;
}
createRoot(document.getElementById('root')).render(<App />);
