export const sites = [
  ['strata-home', 'Strata Staff Global', 'https://stratastaffglobal.com/', 'Public', 99],
  ['trackdev', 'TrackDev', 'https://dev.stratastaff.com/board', 'Public Internal', 99],
  ['escalations', 'Escalations', 'https://escalations.stratastaffglobal.com/', 'Public Internal', 99],
  ['newsletter', 'Newsletter Analytics', 'https://newsletter-analytics.stratastaff.com/', 'Public Internal', 99],
  ['cng-tickets', 'CNG Tickets', 'https://cng-tickets.stratastaff.com/login.php', 'Public Internal', 99],
  ['client-feedback', 'Client Feedback', 'https://clients-feedback.stratastaff.com/feedback.php', 'Public Internal', 99],
  ['scorecard', 'Strata Capacity Test', 'https://stratastaffglobal.com/scorecard/', 'Public', 99],
  ['icp-access', 'ICP Access', 'https://stratastaffglobal.com/icp/icp-login.php', 'Public Internal', 99],
  ['srf-login', 'Staff Login (SRF)', 'https://stratastaff.com/srf/admin/login.php', 'Public Internal', 99],
  ['signatures', 'Email Signature Generator', 'https://onboarding.stratastaffglobal.com/banner/stratastaff/', 'Public Internal', 99],
  ['strata-systems', 'Strata Systems Dashboard', 'https://strata-staff-systems.vercel.app/', 'Public', 99],
  ['grafana-private', 'GRAFANA Monitoring Servers', 'http://172.16.1.243:3000/', 'Private On-Premise', 99],
  ['support', 'Support', 'https://support.stratastaffglobal.com/', 'Public Internal', 99],
  ['requisition', 'Requisition', 'https://requisition.stratastaffglobal.com/', 'Public Internal', 99],
  ['afm', 'AFM', 'https://afm.stratastaffglobal.com/', 'Public Internal', 99],
  ['analytics', 'Analytics', 'https://analytics.stratastaffglobal.com/', 'Public Internal', 99],
  ['dashboard', 'Dashboard', 'https://dashboard.stratastaffglobal.com/', 'Public Internal', 99],
  ['ca-hr-jobs', 'Canada HR Jobs', 'https://stratastaffglobal.com/ca/hr-jobs/', 'Public', 99],
  ['hr-jobs', 'HR Jobs', 'https://stratastaffglobal.com/hr-jobs/', 'Public', 99],
  ['academy', 'Academy', 'https://academy.stratastaffglobal.com/', 'Public', 99],
  ['crm', 'CRM', 'https://crm.stratastaffglobal.com/', 'Public Internal', 99],
  ['learning', 'Learning Portal', 'https://learning.stratastaffglobal.com/public/', 'Public', 99]
].map(([id, name, url, group = 'Public Internal', slaTarget = 99]) => ({ id, name, url, group, slaTarget }));
